name: Remove Assignee on Done

on:
  workflow_dispatch:
  project_card:
    types: [moved]

permissions:
  issues: write

jobs:
  clear_assignee:
    runs-on: ubuntu-latest
    steps:
      - name: Check if issue was moved to Done
        id: check_done
        run: |
          echo "Column name: ${{ github.event.project_card.column_name }}"
          
          # Check if the project card was moved to the "Done" column (adjust based on your column name)
          if [[ "${{ github.event.project_card.column_name }}" == "Done" ]]; then
            echo "moved_to_done=true" >> $GITHUB_ENV
          else
            echo "moved_to_done=false" >> $GITHUB_ENV
          fi

      - name: Debug Content URL
        run: echo "Content URL: ${{ github.event.project_card.content_url }}"

      - name: Extract Issue Number
        id: extract_issue
        run: |
          # Extract issue number from the content_url
          issue_number=$(echo "${{ github.event.project_card.content_url }}" | grep -oE '[0-9]+$')
          echo "Issue Number: $issue_number"
          echo "issue_number=$issue_number" >> $GITHUB_ENV

      - name: Remove Assignee
        if: env.moved_to_done == 'true'  # Remove `${{ }}`
        uses: octokit/request-action@v2.x
        with:
          route: DELETE /repos/:owner/:repo/issues/:issue_number/assignees
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          issue_number: ${{ env.issue_number }}
          assignees: ${{ github.actor }} # Or replace with the specific assignee to be removed
